services:
  postgres:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=soroban_events
      - POSTGRES_USER=sink
      - POSTGRES_PASSWORD=sink
    volumes:
      - sink_pg_data:/var/lib/postgresql/data

volumes:
  sink_pg_data:
